apiVersion: apps/v1
kind: Deployment
metadata:
  name: pxe
  labels:
    app: pxe
    kubernetes.azure.com/generator: devhub
  namespace: kube-node-lease
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pxe
  template:
    metadata:
      labels:
        app: pxe
    spec:
      containers:
        - name: pxe
          image: acrworkflow1722973530004.azurecr.io/image-workflow-1725373058117:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
