apiVersion: v1
kind: Service
metadata:
  name: pxe
  namespace: kube-node-lease
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: pxe
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000